### ISSUE TITLE
Popup behaviour changes

### ISSUE THREAD

**Issue by ericawright** [mozilla/CookieRestrictionsShield#2]
We might want the popup to have an option to disable study after user clicks "yes",
or, we might want to have a checkbox that allows the user to disable the study,
or, we might want to disable TP on this site when the user clicks "yes"

**Comment by groovecoder** [comment]
@tanvihacks - which UX would you like to go with?

When the user answers "Yes" to the pop-up: "Did you reload this page to resolve loading issues?" should we ...

1. Include a checkbox: "Disable privacy protections on this page" // i.e., Disable Protection on this page
2. Include a checkbox: "Disable privacy protections on all pages" // i.e., Disable Study

**Comment by ericawright** [comment]
from the phd updates: 
```
If the user clicks “Yes(broken)”, we will disable protection for the user.  
If they click No, we will not. 
In addition, we will add a checkbox to the notification.  
The checkbox will not be checked automatically.  
It will ask the user if they want to “Disable Privacy Study”
```
