### ISSUE TITLE
On disable study, populate telemetry ping.

### ISSUE THREAD

**Issue by ericawright** [mozilla/CookieRestrictionsShield#23]
When the user clicks the disable study button, we are sending a telemetry ping with a lot of the timing events unpopulated. Can we populate these?

**Comment by ericawright** [comment]
@groovecoder  should we perhaps add a field like "user_disabled_study" to the ping instead?

**Comment by groovecoder** [comment]
Shield automatically sends a ping on disabling the study ...

```
{
  "version": 3,
  "study_name": "cookie-restrictions-shield@mozilla.org",
  "branch": "Control",
  "addon_version": "1.0.0",
  "shield_version": "5.0.3",
  "type": "shield-study",
  "data": {
    "study_state": "user-disable",
    "study_state_fullname": "user-disable"
  },
  "testing": true
}
```
(Note: not sure why this says `"branch": "Control"` - have you seen that before?

It may be that's enough to do the analysis `WHERE study_name='cookie-restrictions-shield@mozilla.org' AND data.study_state='user-disable'`

**Comment by ericawright** [comment]
yes, the branch is the variation - so either "Control" or "CookiesBlocked" we get that from shield with every ping. Okay, I didn't notice the data portion of the ping before, cool. We can close this then, so long as it is recognizable as a disable action
