### ISSUE TITLE
# of trackers trying to read/write cookies (integer)

### ISSUE THREAD

**Issue by ericawright** [mozilla/CookieRestrictionsShield#36]
Number of trackers trying to read/write cookies (integer)
We need to include this in the telemetry ping

**Comment by ericawright** [comment]
@ehsan could you give us some guidance here?

**Comment by jens1o** [comment]
A user on twitter asked whether we can show this number publicly btw.

**Comment by ehsan** [comment]
We talked about this on slack.  Right now we only keep track of whether a document has seen trackers' access to cookies/storage being blocked at all, not a count of how many times per tracker, so this isn't possible without landing new code in Gecko unfortunately...

**Comment by jens1o** [comment]
Okay, thankyou.
