### ISSUE TITLE
report these prefs with the ping 

### ISSUE THREAD

**Issue by ericawright** [mozilla/CookieRestrictionsShield#49]
"browser.contentblocking.trackingprotection.ui.enabled"
      "browser.contentblocking.fastblock.ui.enabled"
      "browser.contentblocking.fastblock.control-center.ui.enabled"
      "browser.contentblocking.trackingprotection.control-center.ui.enabled"
"browser.contentblocking.enabled"
      "browser.contentblocking.ui.enabled"
      "browser.contentblocking.rejecttrackers.ui.recommended"
      "browser.contentblocking.rejecttrackers.control-center.ui.enabled"
      "browser.contentblocking.cookies-site-data.ui.reject-trackers.recommended"
      "browser.contentblocking.cookies-site-data.ui.reject-trackers.enabled"
      "browser.contentblocking.reportBreakage.enabled"
      "urlclassifier.trackingAnnotationTable"
      "urlclassifier.trackingAnnotationWhitelistTable"
"security.pki.distrust_ca_policy"

**Comment by chorliya** [comment]
hey, just btw., including all of those quotation marks (`""`) totally wrecks out chances of using the information on the page; like, for example, to copy-and-search for the about:config entries in question. :$

<pre>pre</pre>
