### ISSUE TITLE
Enable Circle CI for linting and building add-on per PR

### ISSUE THREAD

**Issue by pdehaan** [mozilla/CookieRestrictionsShield#55]
Possibly not super valuable, given how close we are to the deadline, but it may be nice to enable Circle-CI for this repo and at a minimum run `npm test` and `npm run lint` so we don't have any last minute bugs sneak in that can be caught by the linters.

**Comment by ericawright** [comment]
It'll be the same situation as fastblock - which has seemed to be a huge pain so far with all the timeouts....
