### ISSUE TITLE
Onboarding experience overlaps w/ doorhanger

### ISSUE THREAD

**Issue by pdehaan** [mozilla/CookieRestrictionsShield#69]
![menubar_and_firefox_nightly](https://user-images.githubusercontent.com/557895/45243312-2d5b2d00-b2a8-11e8-8965-12f2a8a851ec.png)

Not sure if we can control Z-order and if one dialog should have a higher priority than the other, or if we should suppress the dialog if the onboarding panel is visible (if we can control that).

Clicking the doorhanger doesn't bring it above the onboarding panel, but it isn't obscuring anything important (just the Nightly logo), so not really a huge deal either way.

**Comment by ericawright** [comment]
we talked about this, and it's not a concern
