### ISSUE TITLE
The study doorhanger is not displayed on latest Firefox Beta 63.0b4 build

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/CookieRestrictionsShield#70]
**[Affected versions]:**
- Firefox Beta 63.0b4

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- The `shieldStudy.logLevel` string pref with `All` value was added on a new profile.
- The `extensions.cookie-restrictions_shield_mozilla_org.test.variationName` string pref was added on the same profile with `CookiesBlocked` value.
- The latest Cookie Restriction build from 09/05/2018 found in the tracking bug [1485518](https://bugzilla.mozilla.org/show_bug.cgi?id=1485518) was saved locally.

**[Steps to reproduce]:**
1. Start latest Firefox Beta 63.0b4 build with the profile from prerequisites.
2. Navigate to `about:addons` page and click on `Extensions` section from left side of the page.
3. Drag and drop the Cookie Restriction build saved on the add-ons page and confirm that you wish to install it.
4. Navigate to a website that has tracking cookies (eg: https://www.washingtonpost.com).
5. Refresh the page and after it is fully loaded, look for the Cookie Restriction doorhanger.
6. If the doorhanger is not displayed, refresh again the page several times (no more than 6 times) and wait for it to fully load each time.

**[Expected result]:**
- The Cookie Restriction study doorhanger is correctly displayed at least once in 6 refreshes on latest Firefox Beta v63.0b4.

**[Actual result]:**
- The Cookie Restriction study doorhanger is not displayed at all on latest Firefox beta v63.0b4.

**[Additional Notes]:**
- The study doorhanger is correctly displayed within 6 refreshes on latest Firefox Nightly build.
- Since the study should run on Beta channel, this is a blocker issue.

**Comment by TanviHacks** [comment]
Was this an installation issue?  Or does the addon install and function on beta, and this is an issue just with the reload button?

**Comment by pdehaan** [comment]
I can reproduce this locally too using the latest signed XPI from Bugzilla (as of a few hours ago) and when building locally:


```
TypeError: browser.study is undefined, can't access property "onEndStudy" of it background.js:49:5
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
  transaction    resource://gre/modules/IndexedDB.jsm:349:39
  objectStore    resource://gre/modules/IndexedDB.jsm:377:23
  getStore       resource://normandy/lib/AddonStudies.jsm:82:10
  getAll         resource://normandy/lib/AddonStudies.jsm:204:12
  InterpretGeneratorResume self-hosted:1255:8 next self-hosted:1210:9 
```

<img width="924" alt="bcon" src="https://user-images.githubusercontent.com/557895/45314938-f1aea600-b4e7-11e8-8b46-9ba38d288a42.png">

**Comment by pdehaan** [comment]
I just noticed that it looks like the buttons are reversed on Windows... (Using Beta channel 63.0b4 (64-bit) on Win10):

![image](https://user-images.githubusercontent.com/557895/45330524-baa5b800-b51a-11e8-8d88-a1ea9f1ba9af.png)

**Comment by TanviHacks** [comment]
I believe that is intended.  I recall the buttons are switched on some
platforms.
