### ISSUE TITLE
UI/UX inconsistencies between the "Firefox Survey" door hanger from the PHD and the pi-request email

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/CookieRestrictionsShield#75]
[Notes]:
- Since the PHD mentiones the "Page broken" checkbox from the door hanger, we consider that the UI presented in the pi-request is the correct one (top of 11th page https://goo.gl/dN7azp)

[Affected versions]:
- Beta 63.0b4
- Cookie Restrictions 1.0.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The shieldStudy.logLevel string pref with All value was added on a new profile.
- The extensions.cookie-restrictions_shield_mozilla_org.test.variationName string pref was added on the same profile with CookiesBlocked value.
- Cookie Restrictions .xpi is installed ([link](https://bugzilla.mozilla.org/show_bug.cgi?id=1485518#c28)). 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.washingtonpost.com website.
3. Reload the page until the "Survey" door hanger is displayed (max 6 times).
4. Observe the "Survey" door hanger.

[Expected result]:
- A door hanger containing the following elements is displayed:
-> "Firefox Survey: Did you reload this page because it wasn't working correctly?" text;
-> "Disable Privacy Study" checkbox;
-> No (works) & Yes (broken) buttons;
-> Beta logo on the top left side of the door hanger.

[Actual result]:
- A door hanger containing the following elements is displayed:
-> "Firefox Survey: Why did you reload this page?" text;
-> Page Was Broken & Other reason buttons;
-> Beta logo on the top left side of the door hanger.

[Additional Notes]:
- Added a screenshot with the issue:

![6](https://user-images.githubusercontent.com/26000308/45351345-9ef3ed80-b5be-11e8-9234-be181ffe5cce.png)

**Comment by TanviHacks** [comment]
The checkbox UI was removed from the PHD.  The checkbox with “disable privacy study” is intentionally removed from the extension.
