### ISSUE TITLE
"Firefox Survey" door hanger is wrongly triggered after manually disabling content blocking

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/CookieRestrictionsShield#78]
[Affected versions]:
- Beta 63.0b4
- Cookie Restrictions 1.0.3

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The `shieldStudy.logLevel` string pref with All value was added on a new profile.
- The `extensions.cookie-restrictions_shield_mozilla_org.test.variationName` string pref was added on the same profile with CookiesBlocked value.
- Cookie Restrictions .xpi is installed ([link](https://bugzilla.mozilla.org/show_bug.cgi?id=1485518#c28)). 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.washingtonpost.com website.
2. Click on the "Information" button from the Address Bar.
3. Click the "Disable Blocking For This Site" button from the Control Center.
4. Wait for the page to automatically reload and observe what happens next.
(In case that the door hanger is not displayed after the first reload, refresh the page maximum 6 times)

[Expected result]:
- "Firefox Survey" door hanger is not triggered and displayed anymore.

[Actual result]:
- "Firefox Survey" door hanger is triggered and displayed.

[Additional Notes]:
- Added a screen recording the issue:

![survey pop up](https://user-images.githubusercontent.com/26000308/45362990-f2763380-b5de-11e8-8436-30c11916c314.gif)

**Comment by ericawright** [comment]
this is expected, since we are seeing the doorhanger on sites with and without trackers, and with and without content blocking.
